# Configuration of the GitHub pages integration
theme: jekyll-theme-minimal
baseurl: /chor-js
layouts_dir : docs/_layouts
data_dir: docs/_data
include:
  - docs
exclude:
  - assets
  - node_modules
  - lib
  - resources
  - test
  - karma.conf.js
  - LICENSE
  - package.json